# Generated by Django 3.2.5 on 2021-07-08 15:24

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('FU', 'full'), ('RE', 'reserve'), ('FR', 'free')], default='FR', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
