# Generated by Django 3.2.5 on 2021-07-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('FR', 'free'), ('RE', 'reserve'), ('FU', 'full')], default='fr', max_length=10)),
            ],
        ),
    ]
