# Generated by Django 3.2.5 on 2021-07-08 13:02

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_alter_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='table',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('FR', 'free'), ('FU', 'full'), ('RE', 'reserve')], default='FR', max_length=10),
        ),
    ]
